import type { Metadata } from 'next';
import { Montserrat, Russo_One, Tektur } from 'next/font/google';
import './globals.scss';

const geistSans = Montserrat({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Russo_One({
    variable: '--font-geist-mono',
    subsets: ['latin'],
    weight: '400',
});

const geistTek = Tektur({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Token Twist',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} ${geistTek.variable}`}>{children}</body>
        </html>
    );
}
